"""Add M4 optimizer fields to migration_plan

Revision ID: 20260903_01_phase4_m4
Revises: 20260829_01
Create Date: 2026-09-03 10:11:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20260903_01_phase4_m4'
down_revision = '20260829_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Migration 20260829_01 bootstraps the schema via Base.metadata.create_all(),
    # which reflects whatever columns exist on the *current* model classes — so on
    # a database that's never run these migrations before, these columns already
    # exist. Guard each add_column so this migration is idempotent for both a
    # fresh database and an older one that predates this revision.
    bind = op.get_bind()
    existing_columns = {col["name"] for col in sa.inspect(bind).get_columns("migration_plan")}
    if "priority_score" not in existing_columns:
        op.add_column('migration_plan', sa.Column('priority_score', sa.Float(), nullable=True))
    if "confidence" not in existing_columns:
        op.add_column('migration_plan', sa.Column('confidence', sa.Float(), nullable=True))
    if "optimizer_version" not in existing_columns:
        op.add_column('migration_plan', sa.Column('optimizer_version', sa.String(length=32), nullable=True))
    if "constraints" not in existing_columns:
        op.add_column('migration_plan', sa.Column('constraints', sa.JSON(), nullable=True))
    op.alter_column('migration_plan', 'wave', existing_type=sa.Integer(), nullable=True)

    # Backfill constraints as empty lists
    op.execute("UPDATE migration_plan SET constraints = '[]' WHERE constraints IS NULL")
    op.alter_column('migration_plan', 'constraints', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('migration_plan', 'wave', existing_type=sa.Integer(), nullable=False)
    op.drop_column('migration_plan', 'constraints')
    op.drop_column('migration_plan', 'optimizer_version')
    op.drop_column('migration_plan', 'confidence')
    op.drop_column('migration_plan', 'priority_score')
    # ### end Alembic commands ###
